version: '3'
services:
  ztsphp:
    build: ${PWD}/ztsphp
    container_name: ztsphp
    volumes:
      - ${PWD}/ztsphp:/var/www/html
    command: bash -c "chmod 777 /var/www/html && php-fpm"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 81:80
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/nginx:/var/www/html
    depends_on:
      - ztsphp
